# Generated by Django 4.0.1 on 2022-01-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_origins_delete_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origins',
            name='Range',
        ),
        migrations.AddField(
            model_name='origins',
            name='Percentage',
            field=models.TextField(default=1, max_length=10, verbose_name='Percentage'),
            preserve_default=False,
        ),
    ]
